# app/Dockerfile

# Use a imagem base desejada
FROM nginx:alpine

# Copie os arquivos da aplicação para o diretório do servidor web no contêiner
COPY . /usr/share/nginx/html

# Exponha a porta 80
EXPOSE 80
